#!/bin/zsh
# Sichern aller aufgelisteten Rechner auf ein angestecktes Laufwerk
# BS_UUID=03417033-3745-4ae7-9451-efafcbb9124e
BS_MOUNT=/mnt/BackSnap 
# BS_MOUNT=/mnt/@BackSnap
BS_JAR=/usr/local/bin/backsnap.jar
BS_HOST=manjaro18
# mount aus fstab ;-)
# [ -d $BS_MOUNT/@snapshots ] || mount $BS_MOUNT
# sudo mount -o noatime,subvol=/,compress=zstd:9 UUID=$BS_UUID $BS_MOUNT
# wenn das mounten nicht geklappt hat, ABBRECHEN 
# [ -d $BS_MOUNT/@snapshots ] || { echo "Das mounten war nicht erfolgreich"; exit; }
[ -d $BS_MOUNT/$BS_HOST ] || { echo "Für $BS_HOST gibt es keinen mountpoint"; exit; }

function backup {
    BS_SOURCE="$1"
    BS_DEST="$BS_MOUNT/$2"
#    echo "java -jar $BS_JAR $BS_SOURCE $BS_DEST"
# This script has to be run in a terminal with sudo to get the grapical version !
    java -jar $BS_JAR -g -a -o -m $BS_SOURCE $BS_DEST || exit
# alternative cli-version is called:    
#   java -jar $BS_JAR $BS_SOURCE $BS_DEST || exit    
    echo  "OK"
}

# lokal sichern
backup /     manjaro18
backup /home manjaro18.home

# server sichern
backup root@server:/ server
backup root@server:/home server.home
backup root@server:/srv server.srv

# jitsi sichern
backup root@jitsim1:/ jitsim1
backup root@jitsim1:/home jitsim1.home
backup root@jitsim1:/opt/hst jitsim1.hst
backup root@jitsim1:/opt/hugo jitsim1.hugo

# laptop sichern 
backup root@notebook: notebook
backup root@notebook:/home notebook.home

# gast sichern
# backup root@gast:/ gast
# backup root@gast:/home gast.home

sync
# umount $BS_MOUNT
echo "fertig"
